version: "2"

services:
  api:
    depends_on:
      - "db"
    build: "./sweet_app"
    ports:
      - "3000:3000"
    volumes:
      - "./sweet_app:/api"
      - "./sweet_app/bundle:/usr/local/bundle"
  db:
    image: "postgres:9.5.4"


  #redis:
    #image: "redis:3.2.3"

