version: "2"

volumes:
  api_vol:
  postgres:
  redis:

services:
  api:
    build: "./sweet_app"
    ports:
      - "3010:3010"
    volumes:
      #- "api_vol:${PWD}/sweet_app:/api"
      - "${PWD}/sweet_app:/api"
    depends_on:
      - "postgres"
      - "redis"

  postgres:
    image: "postgres:9.5.4"
    ports:
      - "3011:5432"
    volumes:
      - "postgres:/var/lib/postgres/data"

  redis:
    image: "redis:3.2.3"
    ports:
      - "3012:6379"
    volumes:
      - "redis:/var/lib/redis/data"
