version: "2"

services:
  api:
    depends_on:
      - "postgres"
    build: "./sweet_app"
    ports:
      - "3000:3000"
    volumes:
      #- "api_vol:${PWD}/sweet_app:/api"
      #- "${PWD}/sweet_app:/api"
      - "./sweet_app:/api"
  postgres:
    image: "postgres:9.5.4"
    environment:
      - "POSTGRES_USER=api"
      - "POSTGRES_PASSWORD=sekret"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgres/data"

volumes:
  #api_vol:
  postgres:
