#development: &default
  #adapter: postgresql
  #encoding: unicode
  #database: postgres
  #pool: 5
  #username: postgres
  #password:
  #host: db
#
#test:
  #<<: *default
  #database: sweet_app_test

development:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_development?') %>

test:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_test?') %>
