development: &default
  adapter: postgresql
  encoding: unicode
  #database: sweet_app_dev
  database: postgres
  pool: 5
  username: postgres
  #password: sekret
  password:
  #host: localhost
  host: db

test:
  <<: *default
  database: sweet_app_test
